services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/config_items.json:/app/config_items.json
      - ./backend/parrillada.conf:/app/parrillada.conf
    #ports:
    #  - "8000:8000"
    networks:
      - red_asado

  frontend:
    image: nginx:alpine
    container_name: frontend-asado
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - red_asado
    depends_on:
      - backend
networks:
  red_asado:
    driver: bridge
